# Generated by Django 5.2.12 on 2026-03-26 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting_style', '0001_initial'),
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_roadmap',
            name='style',
        ),
        migrations.AddField(
            model_name='ai_roadmap',
            name='fight_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fighting_style.fighting_style'),
        ),
    ]
