# Generated by Django 5.2.12 on 2026-03-26 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighting_style', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='performance_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('feedback', models.CharField(max_length=20)),
                ('ai_suggestion', models.TextField()),
                ('tested_time', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fighting_style.fighting_style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_time'],
            },
        ),
    ]
