# Generated by Django 5.2.12 on 2026-03-26 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighting_style', '0001_initial'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance_test',
            name='style',
        ),
        migrations.AddField(
            model_name='performance_test',
            name='fight_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fighting_style.fighting_style'),
        ),
        migrations.AlterField(
            model_name='performance_test',
            name='ai_suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='performance_test',
            name='feedback',
            field=models.CharField(choices=[('Correct', 'Correct'), ('Incorrect', 'Incorrect'), ('Need_Improvement', 'Need Improvement')], max_length=20),
        ),
    ]
