# Generated by Django 5.2.12 on 2026-03-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fighter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter_profile',
            name='profile_picture',
        ),
    ]
