# Generated by Django 5.2.12 on 2026-03-26 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=100)),
                ('subscription_start_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_end_date', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
